import {
  Airplay,
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowsClockwise,
  BellSimple,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  CassetteTape,
  ChatsCircle,
  Check,
  CornersIn,
  CornersOut,
  Crown,
  CurrencyDollar,
  Desktop,
  DotsThreeVertical,
  Heart,
  Info,
  Lightning,
  MagnifyingGlass,
  Moon,
  Pause,
  PictureInPicture,
  Play,
  Plus,
  PlusCircle,
  Screencast,
  ShareFat,
  SignOut,
  SpeakerHigh,
  SpeakerLow,
  SpeakerNone,
  Sun,
  Trash,
  TriangleDashed,
  User,
  Users,
  Warning,
  Waveform,
  X
} from "@phosphor-icons/react";

const USED_ICONS = [
  { Icon: Sun, name: "Sun" },
  { Icon: Moon, name: "Moon" },
  { Icon: Waveform, name: "Waveform" },
  { Icon: Desktop, name: "Desktop" },
  { Icon: MagnifyingGlass, name: "MagnifyingGlass" },
  { Icon: BellSimple, name: "BellSimple" },
  { Icon: PlusCircle, name: "PlusCircle" },
  { Icon: Plus, name: "Plus" },
  { Icon: Trash, name: "Trash" },
  { Icon: Play, name: "Play" },
  { Icon: Pause, name: "Pause" },
  { Icon: ArrowClockwise, name: "ArrowClockwise" },
  { Icon: ArrowCounterClockwise, name: "ArrowCounterClockwise" },
  { Icon: CornersIn, name: "CornersIn" },
  { Icon: Heart, name: "Heart" },
  { Icon: ArrowsClockwise, name: "ArrowsClockwise" },
  { Icon: ShareFat, name: "ShareFat" },
  { Icon: User, name: "User" },
  { Icon: DotsThreeVertical, name: "DotsThreeVertical" },
  { Icon: Check, name: "Check" },
  { Icon: X, name: "X" },
  { Icon: Info, name: "Info" },
  { Icon: Warning, name: "Warning" },
  { Icon: CurrencyDollar, name: "CurrencyDollar" },
  { Icon: Crown, name: "Crown" },
  { Icon: CaretUp, name: "CaretUp" },
  { Icon: CaretDown, name: "CaretDown" },
  { Icon: Users, name: "Users" },
  { Icon: CassetteTape, name: "CassetteTape" },
  { Icon: ChatsCircle, name: "ChatsCircle" },
  { Icon: CaretLeft, name: "CaretLeft" },
  { Icon: CaretRight, name: "CaretRight" },
  { Icon: Lightning, name: "Lightning" },
  { Icon: PictureInPicture, name: "PictureInPicture" },
  { Icon: SpeakerHigh, name: "SpeakerHigh" },
  { Icon: SpeakerLow, name: "SpeakerLow" },
  { Icon: SpeakerNone, name: "SpeakerNone" },
  { Icon: TriangleDashed, name: "TriangleDashed" },
  { Icon: CornersOut, name: "CornersOut" },
  { Icon: Airplay, name: "Airplay" },
  { Icon: Screencast, name: "Screencast" },
  { Icon: SignOut, name: "SignOut" }
];

export {
  Sun,
  SignOut,
  CassetteTape,
  ChatsCircle,
  SpeakerHigh,
  SpeakerLow,
  SpeakerNone,
  CornersOut,
  TriangleDashed,
  Plus,
  CornersIn,
  Moon,
  Desktop,
  Warning,
  MagnifyingGlass,
  BellSimple,
  PictureInPicture,
  Lightning,
  PlusCircle,
  Trash,
  Waveform,
  Airplay,
  Screencast,
  X,
  Heart,
  ArrowsClockwise,
  ShareFat,
  DotsThreeVertical,
  Check,
  Info,
  CurrencyDollar,
  Crown,
  Play,
  Pause,
  CaretUp,
  CaretLeft,
  CaretRight,
  CaretDown,
  Users,
  User,
  ArrowClockwise,
  ArrowCounterClockwise,
  USED_ICONS
};
