import {
  ArrowsClockwise,
  CaretDown,
  CaretUp,
  CassetteTape,
  ChatsCircle,
  Check,
  Crown,
  CurrencyDollar,
  Desktop,
  DeviceMobile,
  DotsThreeVertical,
  Heart,
  Info,
  Lightning,
  Moon,
  Panorama,
  PlusCircle,
  ShareFat,
  Sun,
  Trash,
  Users,
  Video,
  Warning
} from "@phosphor-icons/react/dist/ssr";

const USED_ICONS = [
  { Icon: Sun, name: "Sun" },
  { Icon: Moon, name: "Moon" },
  { Icon: Desktop, name: "Desktop" },
  { Icon: PlusCircle, name: "PlusCircle" },
  { Icon: Trash, name: "Trash" },
  { Icon: Heart, name: "Heart" },
  { Icon: ArrowsClockwise, name: "ArrowsClockwise" },
  { Icon: ShareFat, name: "ShareFat" },
  { Icon: DotsThreeVertical, name: "DotsThreeVertical" },
  { Icon: Check, name: "Check" },
  { Icon: Info, name: "Info" },
  { Icon: Warning, name: "Warning" },
  { Icon: CurrencyDollar, name: "CurrencyDollar" },
  { Icon: DeviceMobile, name: "DeviceMobile" },
  { Icon: Video, name: "Video" },
  { Icon: Panorama, name: "Panorama" },
  { Icon: Crown, name: "Crown" },
  { Icon: CaretUp, name: "CaretUp" },
  { Icon: CaretDown, name: "CaretDown" },
  { Icon: Users, name: "Users" },
  { Icon: CassetteTape, name: "CassetteTape" },
  { Icon: ChatsCircle, name: "ChatsCircle" },
  { Icon: Lightning, name: "Lightning" }
];

export {
  Sun,
  CassetteTape,
  ChatsCircle,
  Moon,
  Desktop,
  Lightning,
  PlusCircle,
  Trash,
  Heart,
  ArrowsClockwise,
  ShareFat,
  DotsThreeVertical,
  Check,
  Info,
  Warning,
  CurrencyDollar,
  DeviceMobile,
  Video,
  Panorama,
  Crown,
  CaretUp,
  CaretDown,
  Users,
  USED_ICONS
};
