import {
  Airplane,
  Airplay,
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowsClockwise,
  Baseball,
  BellSimple,
  Books,
  Car,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  CassetteTape,
  ChatCircleDots,
  ChatsCircle,
  Check,
  Copyright,
  CornersIn,
  CornersOut,
  Crown,
  CurrencyDollar,
  CurrencyEth,
  Database,
  Desktop,
  DiscordLogo,
  DotsThreeVertical,
  Drone,
  Empty,
  Eye,
  FilmReel,
  ForkKnife,
  FunnelSimple,
  GameController,
  GraduationCap,
  Handshake,
  Hash,
  Heart,
  Heartbeat,
  Info,
  Island,
  Leaf,
  Lightning,
  Link,
  MagnifyingGlass,
  MaskHappy,
  Microphone,
  Money,
  Moon,
  Newspaper,
  Palette,
  Pause,
  PawPrint,
  PersonSimpleTaiChi,
  PictureInPicture,
  Placeholder,
  Play,
  Plus,
  PlusCircle,
  PottedPlant,
  QuestionMark,
  Screencast,
  ShareFat,
  SignOut,
  Sliders,
  SmileyXEyes,
  SpeakerHigh,
  SpeakerLow,
  SpeakerNone,
  SuitcaseSimple,
  Sun,
  Target,
  Trash,
  TriangleDashed,
  User,
  UserCheck,
  UserPlus,
  Users,
  VideoCamera,
  Warning,
  Waveform,
  WifiHigh,
  WifiX,
  X,
  XLogo,
  YoutubeLogo
} from "@phosphor-icons/react";

const USED_ICONS = [
  { Icon: Sun, name: "Sun" },
  { Icon: Money, name: "Money" },
  { Icon: Moon, name: "Moon" },
  { Icon: Baseball, name: "Baseball" },
  { Icon: Airplane, name: "Airplane" },
  { Icon: UserPlus, name: "UserPlus" },
  { Icon: UserCheck, name: "UserCheck" },
  { Icon: Waveform, name: "Waveform" },
  { Icon: Desktop, name: "Desktop" },
  { Icon: QuestionMark, name: "QuestionMark" },
  { Icon: Sliders, name: "Sliders" },
  { Icon: Palette, name: "Palette" },
  { Icon: Target, name: "Target" },
  { Icon: MaskHappy, name: "MaskHappy" },
  { Icon: Microphone, name: "Microphone" },
  { Icon: GraduationCap, name: "GraduationCap" },
  { Icon: Heartbeat, name: "Heartbeat" },
  { Icon: VideoCamera, name: "VideoCamera" },
  { Icon: Leaf, name: "Leaf" },
  { Icon: Car, name: "Car" },
  { Icon: ForkKnife, name: "ForkKnife" },
  { Icon: Handshake, name: "Handshake" },
  { Icon: Books, name: "Books" },
  { Icon: FilmReel, name: "FilmReel" },
  { Icon: PottedPlant, name: "PottedPlant" },
  { Icon: CurrencyEth, name: "CurrencyEth" },
  { Icon: MagnifyingGlass, name: "MagnifyingGlass" },
  { Icon: BellSimple, name: "BellSimple" },
  { Icon: PlusCircle, name: "PlusCircle" },
  { Icon: Plus, name: "Plus" },
  { Icon: PersonSimpleTaiChi, name: "PersonSimpleTaiChi" },
  { Icon: SuitcaseSimple, name: "SuitcaseSimple" },
  { Icon: FunnelSimple, name: "FunnelSimple" },
  { Icon: GameController, name: "GameController" },
  { Icon: Trash, name: "Trash" },
  { Icon: Play, name: "Play" },
  { Icon: Pause, name: "Pause" },
  { Icon: PawPrint, name: "PawPrint" },
  { Icon: Copyright, name: "Copyright" },
  { Icon: Link, name: "Link" },
  { Icon: Eye, name: "Eye" },
  { Icon: Empty, name: "Empty" },
  { Icon: YoutubeLogo, name: "YoutubeLogo" },
  { Icon: Database, name: "Database" },
  { Icon: Newspaper, name: "Newspaper" },
  { Icon: Island, name: "Island" },
  { Icon: WifiHigh, name: "WifiHigh" },
  { Icon: WifiX, name: "WifiX" },
  { Icon: ArrowClockwise, name: "ArrowClockwise" },
  { Icon: ArrowCounterClockwise, name: "ArrowCounterClockwise" },
  { Icon: CornersIn, name: "CornersIn" },
  { Icon: Heart, name: "Heart" },
  { Icon: ArrowsClockwise, name: "ArrowsClockwise" },
  { Icon: ShareFat, name: "ShareFat" },
  { Icon: User, name: "User" },
  { Icon: DotsThreeVertical, name: "DotsThreeVertical" },
  { Icon: Check, name: "Check" },
  { Icon: X, name: "X" },
  { Icon: Info, name: "Info" },
  { Icon: Warning, name: "Warning" },
  { Icon: CurrencyDollar, name: "CurrencyDollar" },
  { Icon: Crown, name: "Crown" },
  { Icon: CaretUp, name: "CaretUp" },
  { Icon: CaretDown, name: "CaretDown" },
  { Icon: Users, name: "Users" },
  { Icon: CassetteTape, name: "CassetteTape" },
  { Icon: ChatsCircle, name: "ChatsCircle" },
  { Icon: ChatCircleDots, name: "ChatCircleDots" },
  { Icon: CaretLeft, name: "CaretLeft" },
  { Icon: CaretRight, name: "CaretRight" },
  { Icon: Lightning, name: "Lightning" },
  { Icon: SmileyXEyes, name: "SmileyXEyes" },
  { Icon: Placeholder, name: "Placeholder" },
  { Icon: PictureInPicture, name: "PictureInPicture" },
  { Icon: SpeakerHigh, name: "SpeakerHigh" },
  { Icon: SpeakerLow, name: "SpeakerLow" },
  { Icon: SpeakerNone, name: "SpeakerNone" },
  { Icon: TriangleDashed, name: "TriangleDashed" },
  { Icon: CornersOut, name: "CornersOut" },
  { Icon: Airplay, name: "Airplay" },
  { Icon: Hash, name: "Hash" },
  { Icon: Drone, name: "Drone" },
  { Icon: Screencast, name: "Screencast" },
  { Icon: XLogo, name: "XLogo" },
  { Icon: DiscordLogo, name: "DiscordLogo" },
  { Icon: SignOut, name: "SignOut" }
];

export {
  Sun,
  SignOut,
  CassetteTape,
  Airplane,
  Handshake,
  ChatsCircle,
  Sliders,
  Newspaper,
  SuitcaseSimple,
  Copyright,
  Microphone,
  GraduationCap,
  Palette,
  Target,
  CurrencyEth,
  FilmReel,
  PersonSimpleTaiChi,
  QuestionMark,
  MaskHappy,
  VideoCamera,
  Baseball,
  PawPrint,
  Books,
  Leaf,
  ForkKnife,
  PottedPlant,
  Heartbeat,
  Car,
  SpeakerHigh,
  GameController,
  SpeakerLow,
  WifiHigh,
  WifiX,
  YoutubeLogo,
  SpeakerNone,
  Database,
  Hash,
  CornersOut,
  TriangleDashed,
  UserCheck,
  UserPlus,
  Drone,
  Eye,
  Plus,
  SmileyXEyes,
  Island,
  CornersIn,
  Money,
  Moon,
  Desktop,
  Warning,
  FunnelSimple,
  XLogo,
  DiscordLogo,
  MagnifyingGlass,
  BellSimple,
  PictureInPicture,
  Lightning,
  Link,
  PlusCircle,
  Trash,
  Waveform,
  Airplay,
  Screencast,
  X,
  Heart,
  ArrowsClockwise,
  ShareFat,
  DotsThreeVertical,
  Check,
  Info,
  Empty,
  Placeholder,
  CurrencyDollar,
  Crown,
  Play,
  ChatCircleDots,
  Pause,
  CaretUp,
  CaretLeft,
  CaretRight,
  CaretDown,
  Users,
  User,
  ArrowClockwise,
  ArrowCounterClockwise,
  USED_ICONS
};
