-- Migration number: 0004 	 2024-01-15T07:06:40.365Z
CREATE TABLE IF NOT EXISTS AllowedToken (
  id INTEGER PRIMARY KEY AUTOINCREMENT, 
  name TEXT,
  symbol TEXT,
  decimals INTEGER DEFAULT 18,
  address TEXT UNIQUE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
