import {
  Airplane,
  Baseball,
  Books,
  Car,
  Copyright,
  CurrencyEth,
  Desktop,
  Drone,
  FilmReel,
  ForkKnife,
  GameController,
  GraduationCap,
  Handshake,
  Heart,
  Heartbeat,
  Leaf,
  Link,
  MaskHappy,
  Microphone,
  Money,
  Newspaper,
  Palette,
  PawPrint,
  PersonSimpleTaiChi,
  PottedPlant,
  QuestionMark,
  Sliders,
  SuitcaseSimple,
  Target,
  Users,
  VideoCamera
} from "@tape.xyz/winder";

const iconMap = {
  people: Heart,
  music: Sliders,
  podcast: Microphone,
  arts: Palette,
  interests: Target,
  comedy: MaskHappy,
  health: Heartbeat,
  lens: Leaf,
  food: ForkKnife,
  education: GraduationCap,
  literature: Books,
  entertainment: FilmReel,
  garden: PottedPlant,
  crypto: CurrencyEth,
  film: VideoCamera,
  business: SuitcaseSimple,
  family: Users,
  gaming: GameController,
  blockchain: Link,
  howto: QuestionMark,
  news: Newspaper,
  nonprofits: Handshake,
  promotions: Money,
  pets: PawPrint,
  wellness: PersonSimpleTaiChi,
  technology: Desktop,
  sports: Baseball,
  career: Copyright,
  travel: Airplane,
  gadgets: Drone,
  vehicles: Car
};

export const getCategoryIcon = (tag: keyof typeof iconMap) => {
  return iconMap[tag];
};
