export const HOME = '/'
export const EXPLORE = '/explore'
export const LIBRARY = '/library'
export const UPLOAD = '/upload'
export const AUTH = '/auth'
export const LENSTUBE_PATH = '/lt'
export const WATCH_LATER_LIBRARY = '/library/later'
export const RECENTS_LIBRARY = '/library/recents'
export const COMMENTED_LIBRARY = '/library/commented'
export const SETTINGS = '/settings'
export const SETTINGS_MEMBERSHIP = '/settings/membership'
export const SETTINGS_PERMISSIONS = '/settings/permissions'
export const PRIVACY = '/privacy'

export const DISCORD = '/discord'
