export const HOME = '/'
export const EXPLORE = '/explore'
export const FEED = '/feed'
export const NOTIFICATIONS = '/notifications'
export const UPLOAD = '/upload'
export const BYTES = '/bytes'
export const AUTH = '/auth'
export const LENSTUBE_STATS = '/stats'
export const SETTINGS = '/settings'
export const SETTINGS_MEMBERSHIP = '/settings/membership'
export const SETTINGS_PERMISSIONS = '/settings/permissions'
export const SETTINGS_DANGER_ZONE = '/settings/danger'
export const PRIVACY = '/privacy'

export const DISCORD = '/discord'
