#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling and testing project before committing'

# Check Prettier standards
yarn check-format ||
(
    echo '
    
        Prettier Check Failed. Run yarn format, add changes and try commit again.
        
        ';
    false;
)

# Check ESLint Standards
yarn check-lint ||
(
        echo '

        ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.
                
        '
        false; 
)

# Check tsconfig standards
yarn check-types ||
(
    echo '
    
    ❌ Failed Type check ❌
    
    '
    false;
)

echo '

✅✅✅✅ Looks good... committing the changes. ✅✅✅✅

'
