#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling and testing project before committing'

# Check Prettier standards
yarn check-format ||
(
    echo '
    
        🤢🤮🤢🤮 Your styling looks disgusting. 🤢🤮🤢🤮

        Prettier Check Failed. Run yarn format, add changes and try commit again.
        
        ';
    false;
)

# Check ESLint Standards
yarn check-lint ||
(
        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
yarn check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
