DROP TABLE IF EXISTS Verified;
CREATE TABLE IF NOT EXISTS Verified (Id INTEGER PRIMARY KEY AUTOINCREMENT, ProfileId TEXT, CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO Verified (ProfileId) VALUES ('0x01'), ('0x2d');